### ISSUE TITLE
When you release spirit, mobs will aggro onto your ghost prior to being teleported to the graveyard.

### ISSUE THREAD

**Issue by Illuminati2739** [Rochet2/TrinityCore#101]
https://github.com/TrinityCore/TrinityCore/commit/28591fd1658e3e4842d64f330f27c233dc69aad2

Needs to be ported to these branches, present behavior is still bugged as it explains here:

Description:

For some reason, if you release your spirit close to a mob that can aggro onto you, the mob will aggro for a split second and reset. This can be seen easily on boss encounters where you would normally die close to the boss home position. Not necessarily any "negative" issues related to this that I have noticed so far, but definitely not working as intended.

Current behavior:

When you release spirit, mobs will aggro onto your ghost prior to being teleported to the graveyard.

Expected behavior:

Mobs should not aggro onto your ghost when releasing.

Steps to reproduce the problem:

Die close to a mob that can aggro onto you, easily seen on raid bosses
Release spirit while observing creature behavior from a second account
Branch(es): 3.3.5 multivendor

**Comment by Rochet2** [comment]
The bug does not seem to be related to multivendor ( or any other scripts on this repository ).
If this is a bug related to trinitycore, report it on trinitycore repository https://github.com/TrinityCore/TrinityCore/issues.

Also do note that you should be using `multivendor_3.3.5` branch and not `multivendor` branch, in case you are still using the latter one.

**Comment by Illuminati2739** [comment]
https://github.com/TrinityCore/TrinityCore/commit/28591fd1658e3e4842d64f330f27c233dc69aad2

**Comment by Illuminati2739** [comment]
I am sorry Rochet, But i am only here to report something.  I have 3 different cores, one of them is yours, on Original Trinity Branch, this problem is no longer there.
