### ISSUE TITLE
Problem on compilation

### ISSUE THREAD

**Issue by SollStice** [Rochet2/TrinityCore#103]
**Description:**

I've installed the Tmog global diff, worked.
I've installed the Tmog Vendors, crash when compiling

**Current behaviour:**

Error on vendors compilation
https://gist.github.com/SollStice/a8dca7cedbb2601a2a1120c430355451

**Expected behaviour:**

No errors

**Steps to reproduce the problem:**

1. Install diff transmogvendors
2. Cmake
3.compile -> Error
**Branch(es):**
3.3.5

**Operating system:** Windows 10

**Comment by Rochet2** [comment]
The two patches are not really compatible at the moment.
Also the installation seems to have been incomplete since clearly a variable is missing.
If you used `git apply --reject` then you possibly forgot to apply one of the `.rej` files that the command generates.

**Comment by Strazhnik** [comment]
@Rochet2, on last rev transmog script don't work (not found Creature_transmogrify)

**Comment by Rochet2** [comment]
@Strazhnik very likely you forgot to do one of:
- compile
- move new server files after compile
- add creature in DB
- created creature yourself and misspelled the scriptname or forgot it
- missed a part of the patch so the script isnt added properly even if it compiles

If nothing helps, trying again (check that all of the code from the patch is applied, try compile again, try move the new files, try add the creature to DB..)

Most often with such error people simply forgot to move the new server files to server folder after compiling.

**Comment by Strazhnik** [comment]
The script needs to be checked and updated, because npc_text id= 50000 already in use on last rev
