### ISSUE TITLE
It’s impossible to buy items from all vendors.

### ISSUE THREAD

**Issue by Rokmusic** [Rochet2/TrinityCore#105]
It’s impossible to buy items from all vendors. Compilation passed without errors
there is nothing in the logs
in the game, when trying to buy, nothing

TrinityCore 3.3.5 from March 13

Patch installed:
http://www.ac-web.org/forums/showthread.php?232088-C-UPDATE-Template-NPC

I'm sorry. This is my first report.
thank

**Comment by Rochet2** [comment]
The code you refer to is not mine.
It is also not a part of this repository.
This is not a place to ask for help with issues in general, but issues should be related to the codes that are a part of this repository.

Please ask help on the topic you linked or on emulation forums.

**Comment by Rokmusic** [comment]
Once again, I apologize. I installed the patch:
https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmog_3.3.5.diff

I wanted to say that this patch was installed:
http://www.ac-web.org/forums/showthread.php?232088-C-UPDATE-Template-NPC

Thank you so much for the prompt response.

**Comment by Rochet2** [comment]
Are you trying to say that you are unable to transmogrify items?
If so, then you should provide details on the items you tried to use to transmogrify (the equipped item and the item from your bags).
Also provide the transmogrification configuration (it is in worldserver.conf)

**Comment by Rokmusic** [comment]
Not. With the transmographer everything is OK
After installing the patch I can not buy items from any vendors.
Config did not touch or did not even add to the worldserver.conf his settings
(Perhaps a problem because of this?)

I just replaced Worldserver.exe and updated.

PS
Now collected not 3.3.5. Downloaded:
https://github.com/Rochet2/TrinityCore/archive/transmogvendor_3.3.5.zip
And rolled patch:
http://www.ac-web.org/forums/showthread.php?232088-C-UPDATE-Template-NPC
I will test. I will write
(translate.google.com)

Many thanks for your work !! (I always wanted to say it =) It's bad that I started compiling just now.
Благодарю!!

**Comment by Rokmusic** [comment]
Thank you again.
 
PS
It's bad that custom_scripts_loader is processed at the end)
If possible, please make pvp patches - CFBG arena 1x1.
I love FuN)
PSS
There is an old script for a roulette (like in a casino) - text version. If anyone is interested - write.
It would be cool to make it with objects (like a playing table with a ball)
