### ISSUE TITLE
 [dressnpc_3.3.5] Visual bug with Mirror Image

### ISSUE THREAD

**Issue by Infernales** [Rochet2/TrinityCore#109]
**Description:**
Missing model.
https://i.imgur.com/NrufTcW.jpg
**Steps to reproduce the problem:**
1. Create mage
2. Use Mirror Image
**Branch(es):**
dressnpc_3.3.5
**TC rev. hash/commit:** 
2c92872

**Comment by Infernales** [comment]
@Rochet2 In clean TrinityCore, this works correctly.

**Comment by Rochet2** [comment]
Hmm, seems for me it works 66%
https://i.imgur.com/XDtLOXs.png

**Comment by Infernales** [comment]
@Rochet2 Yes, if you use the spell many times, then there is a chance that it will work. In fact, I noticed this about a year ago, but I thought that there was a mistake in TrinityCore. xD

**Comment by Rochet2** [comment]
probably fixed https://i.imgur.com/HqI2nWn.jpg

**Comment by Infernales** [comment]
@Rochet2 Okay thank you.
