### ISSUE TITLE
Reliquary of the Lost 22856

### ISSUE THREAD

**Issue by Rokmusic** [Rochet2/TrinityCore#110]
Hello,
I have encountered a problem while raiding in "The Black Temple" zone.

How to reproduce the bug:

Get inside "The Black Temple".
killed the first bosses :
High Warlord Naj'entus
Supremus
Shade of Akama
Teron Gorefiend
Gurtogg Bloodboil

Try to start "Reliquary of the Lost" Encounter
https://www.wowhead.com/npc=22856/reliquary-of-the-lost

What should happen, what happens instead:
You should be able to start the boss, or even target him. instead, you cant target the boss or start the actual boss event.

gm off. 

Win64. rev of 10.17.2019

**Comment by Rokmusic** [comment]
fix - UPDATE `creature_template` SET `unit_flags` = '64' WHERE `entry` = '22856';

**Comment by Rochet2** [comment]
Better report at https://github.com/TrinityCore/TrinityCore/issues
