### ISSUE TITLE
NpcDress fix 8.3

### ISSUE THREAD

**Issue by hoxton22** [Rochet2/TrinityCore#115]
Hello !
With 8.3, dressnpc don't work, the server won't launch because of there are no implementation for new gnome race :
In objectMgr.cpp, LoadCreatureOutfits function

just add the line under the others :
`{/*RACE_MECHAGNOME*/            37, RACE_GNOME},`

and it should be ok !

**Comment by Rochet2** [comment]
Fixed in https://github.com/Rochet2/TrinityCore/commit/12bdce1a41f36d3abb8425da21c0605196836c44 I guess.
