### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by GnaXi** [Rochet2/TrinityCore#116]
**Description:**

Not able to compile with the latest version of TrinityCore 3.3.5

**Current behaviour:**

Getting the following error:
/home/wow/highrate/TrinityCore/src/server/game/Entities/Item/Transmogrification.cpp:41:25: fatal error: no member named 'transmog' in 'Item'
    itemTransmogrified->transmog = fakeEntry;
    ~~~~~~~~~~~~~~~~~~  ^
1 error generated.
make[2]: *** [src/server/game/CMakeFiles/game.dir/build.make:1198: src/server/game/CMakeFiles/game.dir/Entities/Item/Transmogrification.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1306: src/server/game/CMakeFiles/game.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Expected behaviour:**

Compile without error? :P

**Steps to reproduce the problem:**

1. git remote add rochet2 https://github.com/Rochet2/TrinityCore.git
2. git pull rochet2 transmog_3.3.5
3. compile & make

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

Latest, just pulled from Trinitycore

**Operating system:** 
Ubuntu 19.10

**Comment by Rochet2** [comment]
Travis says it compiles fine and the build started 1 min after you posted.
https://travis-ci.org/github/Rochet2/TrinityCore3.3.5/builds/673774100

The error `no member named 'transmog' in 'Item'` would suggest that not all required changes were applied from the custom code to your core. Make sure `Item` class has the `transmog` field.

**Comment by GnaXi** [comment]
Weirdly enough I deleted the whole thing and started over and it worked.
Not exactly sure what I did different, but it is working now! :)
Thank you for the quick feedback and sorry for the inconvenience!
