### ISSUE TITLE
Player & Item Gossip

### ISSUE THREAD

**Issue by src893** [Rochet2/TrinityCore#119]
Script not compatible with latest trinitycore build and latest gossip system

**Comment by SlntHntr** [comment]
Been having a similar issue lately.  Have used your transmog in the past but lately it's hanging up with overrides on the build.  Specifically in the gossiphelper if I recall.  Will attempt a rebuild and post more detailed info this evening after work.

**Comment by Unwrath** [comment]
That's still an issue. Treeston's pull request fixed few errors, but GossipHello/OnGossipHello is going wild with overrides.

**Comment by Rochet2** [comment]
I assume this is fixed since CI now passes.
Comment back or open a new ticket if still not resolved.
