### ISSUE TITLE
Disable transmog in arena

### ISSUE THREAD

**Issue by Runico** [Rochet2/TrinityCore#12]
hi, rochet2

is this possible disable transmogrification in arena ?

**Comment by Rochet2** [comment]
Sure it is. However I will not be implementing such.
You could for example make the it not apply transmog (edit player.cpp) when you are in an arena.
That is probably enough.

**Comment by Runico** [comment]
```
if (uint32 entry = sTransmogrification->GetFakeEntry(pItem) && !InArena())
```
is this right place to do ?

**Comment by Rochet2** [comment]
think it looks right. Might need to have () around that part before && though.

**Comment by Runico** [comment]
Thank you
