### ISSUE TITLE
Unable to apply multitrainer

### ISSUE THREAD

**Issue by shadowrckts** [Rochet2/TrinityCore#120]
Using most recent compilation of trinitycore (as of yesterday 6/26/2020)
tried to apply multitrainer using gitbash:

$ git apply multitrainer_3.3.5.diff
multitrainer_3.3.5.diff:174: trailing whitespace.
This patch was coded originally by [CyberMist2](https://github.com/CyberMist2). 
multitrainer_3.3.5.diff:201: trailing whitespace.
The NPC is required to have `npcflag` set to `17`. The `trainer_type` can be `0`.
multitrainer_3.3.5.diff:202: trailing whitespace.
In C++ you can pass the trainer entry to `SendTrainerList` function.
error: patch failed: src/server/game/Server/WorldSession.h:459
error: src/server/game/Server/WorldSession.h: patch does not apply

**Comment by Rochet2** [comment]
Try now?
Should work with clean TC.
Otherwise you likely have custom changes or older core than expected for latest patch.

**Comment by shadowrckts** [comment]
Hello,

This is a fresh TC. The patch fails when using git apply command at the start, before building.

Does this patch require your Multivendor to run?

Cheers.

**Comment by Rochet2** [comment]
With core cloned right now it succeeds fine. Are you sure you are using 3.3.5 TC?

```bash
git clone --depth 1 --branch 3.3.5 https://github.com/TrinityCore/TrinityCore.git
cd TrinityCore
git apply multitrainer_3.3.5.diff

multitrainer_3.3.5.diff:174: trailing whitespace.
This patch was coded originally by [CyberMist2](https://github.com/CyberMist2).
multitrainer_3.3.5.diff:201: trailing whitespace.
The NPC is required to have `npcflag` set to `17`. The `trainer_type` can be `0`.
multitrainer_3.3.5.diff:202: trailing whitespace.
In C++ you can pass the trainer entry to `SendTrainerList` function.
warning: 3 lines add whitespace errors.
```

**Comment by shadowrckts** [comment]
Yes, my server has now been running fine (i opted not to follow through with multitrainer since it was the only part not working). I will try with a fresh download of the multitrainer

**Comment by Rochet2** [comment]
I assume that the issue was resolved.
