### ISSUE TITLE
Crash Item::LoadFromDB

### ISSUE THREAD

**Issue by Pirricli** [Rochet2/TrinityCore#123]
When you log in with some characters the server crashes immediately

TrinityCore 3.3.5 + Transmo_3.3.5 patch

515a34f64f200ea0fb9722914b76ab8abd358891

Ubuntu 20.04.01

Crashlog:
https://gist.github.com/Pirricli/bba492f235a563ecb3e34adaf9a7e10f

**Comment by Rochet2** [comment]
Fixed in 71d46c1aebe9f703480d94b8b25063fb026b87ab

**Comment by Pirricli** [comment]
Thank you! I'll test.
