### ISSUE TITLE
TC335 Eluna: Dress NPC conflicts

### ISSUE THREAD

**Issue by Asmodann** [Rochet2/TrinityCore#124]
Hi!

I have some problems to pull dressnpc. I’m using the latest version of https://github.com/ElunaLuaEngine/ElunaTrinityWotlk.
EDIT: I’m using a full fresh repo, no changes and no build.

And I want add the feature dress npc 3.3.5, so I tried to pull it, following the readme in this repo, and this give me conflicts.

How to reproduce it? Follow instructions on https://github.com/Rochet2/TrinityCore/tree/dressnpcs_3.3.5/src/server/scripts/Custom/DressNPCs
git clone latest version of ElunaTrinityWotLK,
Then git remote dress_npc3.3.5 and git pull it

Thanks for your time.

**Comment by Asmodann** [comment]
Hi! Well I founded a solution. But, this is not very smart and you need to know what your are doing, because you’ll not be able to get update of this and you can broke something.
So it’s recommanded to get a first experience with git and development.

Make a copy of your current trinitycore directory to get a bake up if you are missing something.

From https://github.com/TrinityCore/TrinityCore/compare/3.3.5...Rochet2:dressnpcs_3.3.5 copy and paste green lines, file per file, from the git link to your project files. Remove/replace the red lines.

Take care, some changes had another label. Like in CreatureOutfit.cpp where rEntry->femaleDisplayID can be rEntry->model_f and same thing for male model.

You can compare with your current core scripts files. Or wait for errors in compilation and change it.

Hope this can help. :)

**Comment by Rochet2** [comment]
I assume this was fixed or resolved otherwise. The codebases have been updated.
