### ISSUE TITLE
ELunaTC335 + DressNPC + GOmove+Transmog+GOscale Compile Error

### ISSUE THREAD

**Issue by Nupper** [Rochet2/TrinityCore#128]
Compile with DressNPC + GoMove+Transmog+Goscale
![unknown](https://user-images.githubusercontent.com/6026902/102678272-3d5c5980-419f-11eb-9daa-0ccea10a699f.png)

Compile With DressNPC only
![unknown (1)](https://user-images.githubusercontent.com/6026902/102678317-7268ac00-419f-11eb-8114-0bd16a589bda.png)

**Comment by Rochet2** [comment]
The issues should now have been resolved.
