### ISSUE TITLE
Unable to apply transmogs to 1H sword

### ISSUE THREAD

**Issue by dabeer** [Rochet2/TrinityCore#132]
**Description:**
Unable to apply transmog to 1H sword

**Current behaviour:**

Equipped new Avool's Sword of Jin (1H sword) in MH slot, with new The Black Knight (1H sword) in inventory. Talked to transmog vendor, menu option to apply transmog was not presented. Reversed, with The Black Knight equipped and Avool's Sword of Jin in inventory, still no menu item.  Equipped in OH slot, repeated, same behavior observed.

**Expected behaviour:**

Menu option to apply The Black Knight transmog onto Avool's Sword of Jin should have been presented.

**Steps to reproduce the problem:**

1. Clone TC 3.3.5, apply Transmog diff, make, install. Apply transmog vendor template to DB, add npc.
2. Create hunter, level 80, train dual wield. additem Avool's Sword of Jin and The Black Knight. Equip Avool's Sword of Jin in MH slot.
3. Talk to vendor. Select Main Hand. Observe no menu option for The Black Knight.

**Branch(es):**
**TC rev. hash/commit:** 
**TDB version:**  CHANGEME Version of the TrinityCore database
**Operating system:** CHANGEME OS

TC> .server debug
TC> TrinityCore rev. a34519bded8a+ 2021-03-02 23:11:49 +0100 (3.3.5 branch) (Unix, RelWithDebInfo, Static)
Using SSL version: OpenSSL 1.1.1g FIPS  21 Apr 2020 (library: OpenSSL 1.1.1g FIPS  21 Apr 2020)
Using Boost version: 1.67.0
Using MySQL version: 100505
Using CMake version: 3.11.4
Compiled on: Linux 4.18.0-240.10.1.el8_3.x86_64
Automatic database updates are enabled for the following databases: Auth, Characters, World
Worldserver listening connections on port 8085
Realmlist (Realm Id: 1) configured in port 8085
VMAPs status: Enabled. LineOfSight: 1, getHeight: 1, indoorCheck: 1
MMAPs status: Enabled
maps directory located in ../data/maps. Total size: 251987687 bytes
vmaps directory located in ../data/vmaps. Total size: 658130721 bytes
mmaps directory doesn't exist!. Using path: ../data/mmaps
Using enUS DBC Locale as default. All available DBC locales: enUS
Using World DB: TDB 335.21021

**Comment by Rochet2** [comment]
The other item is One Hand and one item is Main Hand.
You cannot transmog One Hand to Main Hand since you can equip the item to Off Hand.

You can disable this restriction in the settings. However, then it is possible to transmogrify items so that their models are the wrong way around in hands for example (main hand model in off hand).
See this setting: https://github.com/Rochet2/TrinityCore/blob/ada1e6ada934a332dc08f5e1504941cf73cc0db0/src/server/worldserver/worldserver.conf.dist#L4154-L4156

**Comment by dabeer** [comment]
With respect - no, both items are One-Hand swords.

**Comment by Rochet2** [comment]
Hmm, seems the item has changed over time or online DBs are wrong/have different info.

In any case, there are other settings that you should look into. For example, the stats count setting may be what is blocking the transformation:
https://github.com/Rochet2/TrinityCore/blob/ada1e6ada934a332dc08f5e1504941cf73cc0db0/src/server/worldserver/worldserver.conf.dist#L4186-L4188

**Comment by Rochet2** [comment]
For me `Transmogrification.IgnoreReqStats = 1` works just fine. I can see the black knight in the menu and transmogrify with it.

**Comment by Rochet2** [comment]
Closing for now as there is no reply
