### ISSUE TITLE
Multitrainer

### ISSUE THREAD

**Issue by Demonasus** [Rochet2/TrinityCore#135]
@Rochet2 I have an issue but unsure if it's an issue or something is simply not supported by the multitrainer.

So i added the multitrainer, added conditions to prevent any warning logs, however i cannot add an option to my gossip_menu_option for Talent Reset or Dual spec, anytime i added more options they do not show. So basically i just want to add a new line to gossip_menu_option for Talent Reset option or Dual Spec and it doesnt recognize it.

Any thoughts?

Thank you

**Comment by Rochet2** [comment]
Maybe show the options you tried?
I don't see why they wouldn't work together.

**Comment by Demonasus** [comment]
https://gyazo.com/0bcb6998cfb44866604844db9a94b09c i simply tried a normal way of adding reset talents to my gossip and it simply does not appear.

**Comment by Demonasus** [comment]
Any updates or suggestions on how to fix this?

**Comment by Rochet2** [comment]
I took a look at the code and it seems that the function that builds the gossip menu `Player::PrepareGossipMenu` requires the creature to be a valid trainer.

In practice, the following are needed for example if the NPC entry is `190012`:
```sql
INSERT INTO `creature_default_trainer` (`CreatureId`, `TrainerId`) VALUES (190012, 190012);
INSERT INTO `trainer` (`Id`, `Type`, `Requirement`, `Greeting`, `VerifiedBuild`) VALUES (190012, 0, 0, 'Wazzaaa', 0);
```
You can use existing rows also, but make sure the `trainer.type` is 0 for class trainer and `trainer.requirement` is 0 to allow training any class.

After that, the options should show up and work.

**Comment by Demonasus** [comment]
Ok that worked ,

what do you mean by
```make sure you match other requirements too, for example that you have enough levels to have talents at all```

**Comment by Rochet2** [comment]
I meant that if you test it ingame, dont test with level 1 character and expect to see a talent menu :D

**Comment by Demonasus** [comment]
Ahhh lol, thanks @Rochet2
