### ISSUE TITLE
Reforge - Custom Items

### ISSUE THREAD

**Issue by Demonasus** [Rochet2/TrinityCore#137]
Hello @Rochet2 

What does Reforge Script require for custom items? So far i havent seen custom items to be recognized by reforge,

Thank you

**Comment by Rochet2** [comment]
One common issue is that stats_count for custom items is usually 10.
It is expected that there are free stat slots on items that are reforgable.

There may be other expectations, but this is most common.

**Comment by Demonasus** [comment]
appreciated.  you are correct, it's stats count 10 is the issue.
