### ISSUE TITLE
the two different transmogrification can use together?

### ISSUE THREAD

**Issue by ryoting** [Rochet2/TrinityCore#14]
if the two different transmogrification can use together?

**Comment by Rochet2** [comment]
Check this out:
http://emudevs.com/showthread.php/33-Trinitycore-Transmogrification-3-3-5a?p=37058&viewfull=1#post37058

**Comment by ConradBunton** [comment]
Transmogvendor and reforging cant be merged to the latest trinitycore ?

**Comment by Rochet2** [comment]
> Transmogvendor and reforging cant be merged to the latest trinitycore ?

Merging works fine. (direct merge)
However you may have run into errors with the diff if TC made changes near the places diff edits.
I updated the diffs now.

**Comment by ConradBunton** [comment]
ok, i'll try

**Comment by Rochet2** [comment]
@ConradBunton It should be noted that merging both transmog and reforging likely results in errors since they edit the same places. You have to manually solve those errors by changing the code.
