### ISSUE TITLE
DressNPC

### ISSUE THREAD

**Issue by ItsMrMedic** [Rochet2/TrinityCore#146]
Are there plans to update this to trinitys current master? Failed to get this to work and can see its merging is failing.

**Comment by Rochet2** [comment]
The merge and build was fixed after https://github.com/Rochet2/TrinityCore/commit/fdf152b79f4eedce8c6dc9d3b7f4f09753c1dc78

I cant test the changes at the moment, so it may or may not work.

**Comment by ItsMrMedic** [comment]
Just another ping that this needs updating Rochet :)

**Comment by ItsMrMedic** [comment]
Is this currently working in TC recent master branch?

**Comment by Rochet2** [comment]
@ItsMrMedic can you tell what kind of errors you get and where?

Merge with latest tc master branch [succeeded 12 hours ago](https://github.com/Rochet2/TrinityCore/actions/runs/4969707984/jobs/8893085344). But I have not tested in game.

**Comment by ItsMrMedic** [comment]
> @ItsMrMedic can you tell what kind of errors you get and where?
> 
> Merge with latest tc master branch [succeeded 12 hours ago](https://github.com/Rochet2/TrinityCore/actions/runs/4969707984/jobs/8893085344). But I have not tested in game.

Nevermind, this was my bad had some custom code that was a little out of date to go alongside this.
