### ISSUE TITLE
SQL syntax on transmog_3.3.5

### ISSUE THREAD

**Issue by okfok** [Rochet2/TrinityCore#152]
Server crashes whenever you log in character
Console output:
```
[1064] You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%u' at line 1
Error while parsing SQL. Core fix required.
```

**Comment by Rochet2** [comment]
Seems I need to go through all of the scripts and change `%u` and similar format characters to `{}`

**Comment by Hyacinthrose** [comment]
Would be greatly appreciated. Same issue here, and I must look good!

**Comment by Rochet2** [comment]
Can you try now?

**Comment by Hyacinthrose** [comment]
No server crash, transmogs stayed from prior characters, new transmogs work too, even after server restart. 
Works for me, thank you very much Rochet. :)

P.s: That Wotlk client side gobject mover is still the best!

**Comment by okfok** [comment]
Everything works fine, ty for keeping repo up to date❤
