### ISSUE TITLE
Multitrainer TrinityCore 335 error m_current_trainer

### ISSUE THREAD

**Issue by McCrowley** [Rochet2/TrinityCore#153]
Hello,
Maybe someone could help me, I want a multi-trainer
for TrinityCore 335   ff0d198  2 weeks ago  patching but getting the error m_current_trainer

VS 2022

Severity Code Description Project File Line Suppression condition
Error C2065 "m_current_trainer": undeclared identifier worldserver C:\TrinityCore3.3.5a -\src\server\game\Server\WorldSession.h 575

// Multitrainer
        uint32 GetCurrentTrainer() const { return m_current_trainer; }
        void SetCurrentTrainer(uint32 entry) { m_current_trainer = entry; }

maybe someone could help me with that

**Comment by Rochet2** [comment]
Did you add the variable like in the patch?
It would be best if you can apply the patch automatically with `git apply` to avoid mistakes
![image](https://github.com/Rochet2/TrinityCore/assets/468816/3b8295bf-f1c5-493c-91b7-d55b1d811774)

**Comment by McCrowley** [comment]
Thank you very much, I'm stupid, I forgot something, that always happens to me. Automatic patching is better, but I use several script cores
I would like to thank them very much:-)
