### ISSUE TITLE
GOMove unnable to apply diff

### ISSUE THREAD

**Issue by Strajkus** [Rochet2/TrinityCore#155]
Hi, I spend over a day trying to get GOMove working on my server. 

Direct merge resulted in "Fatal error LNK1181 ..\scripts\RelWithDebInfo\scripts.lib" 

And diff i am not even able to apply:

![image](https://github.com/Rochet2/TrinityCore/assets/121504920/be90bfe9-d536-494b-85c0-b8eb172a2c41)

I have already installed DressNPC and Transmog without any issue whatsover. 

Its 3.3.5a

**Comment by Rochet2** [comment]
The diff does not apply because of the other custom scripts you have edit the same places (custom_script_loader)
You need to for example use `git apply --reject` and manually fix the failing parts because git does not know how to solve the modifications needed to the changed code.

**Comment by Strajkus** [comment]
That did the trick. Thanks :)
