### ISSUE TITLE
DressNPC - Demon Hunter Compatability

### ISSUE THREAD

**Issue by DJScias** [Rochet2/TrinityCore#17]
**Description**: Considering you track the latest 6x branch from TC you may probably have noticed it went 7x and now allows Demon Hunters.

The addition of DH added 3 new columns character-wise (customDisplay1, customDisplay2, customDisplay3), to deal with the extras chosen at char creation (Tattoo Style, Tattoo Color, Horn Style, Blindfolds). I suppose these four options should be added to the DressNPC functionality sooner or later.

Keep in mind that packet-wise these are not just stored as individual columns, so-to-speak. It's stored as `_worldPacket.append(charInfo.CustomDisplay.data(), charInfo.CustomDisplay.size());` and on altering appearances it is looped through:

``` c++
for (std::size_t i = 0; i < NewCustomDisplay.size(); ++i)
    _worldPacket >> NewCustomDisplay[i];
```

I hope the above information helps you out somehow.

**Current behaviour**: It's not supported.

**Expected behaviour**: Eventually it should be, there's no rush of course. Just making an issue so this is being kept 'track' of so to speak.

**Steps to reproduce the problem**:

N/A

**Branch(es)**: 6x  

**TC hash/commit**:  2be2e41f8434cb0cba30928e75ffaf1f43656ac6

**TDB version**:  Latest

**Operating system**:  N/A

**Comment by Rochet2** [comment]
Just a FYI - I will look into this once TC updates their CascLib

**Comment by Rochet2** [comment]
Added support for the new fields. Also added support for the appearances.
