### ISSUE TITLE
DressNPC merge conflicts. Fresh TC 6.x.

### ISSUE THREAD

**Issue by zapilich** [Rochet2/TrinityCore#18]
Hello. When I tried to fresh install TC 6.x and merge it with DressNPC I got 2 merging conflicts:

remote: Counting objects: 846, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 846 (delta 414), reused 404 (delta 404), pack-reused 360Receiving objects:  99% (838/846), 276.00 KiB | 2
Receiving objects: 100% (846/846), 533.43 KiB | 262.00 KiB/s, done.
Resolving deltas: 100% (581/581), completed with 135 local objects.
From https://github.com/Rochet2/TrinityCore
  branch            dressnpcs_6.x -> FETCH_HEAD
  [new branch]      dressnpcs_6.x -> rochet2/dressnpcs_6.x
Auto-merging src/server/game/World/World.cpp
Auto-merging src/server/game/Handlers/QueryHandler.cpp
Auto-merging src/server/game/Globals/ObjectMgr.h
CONFLICT (content): Merge conflict in src/server/game/Globals/ObjectMgr.h
Auto-merging src/server/game/Globals/ObjectMgr.cpp
CONFLICT (content): Merge conflict in src/server/game/Globals/ObjectMgr.cpp
Auto-merging src/server/game/Entities/Creature/Creature.h
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Rochet2** [comment]
Fixed
