### ISSUE TITLE
MainHand > OneHand transmog

### ISSUE THREAD

**Issue by ghost** [Rochet2/TrinityCore#2]
Hello. Is there any way to implement transmogrification MainHand to OneHand and OneHand to MainHand? I cannot enable Mixed Weapon Types but i need to allow to transmog for ex. Spell Power Daggers to Rogue Daggers and vice versa. 

Thank  you.

**Comment by Rochet2** [comment]
Try editing these lines out:
https://github.com/Rochet2/TrinityCore/blob/b33c7baab63f6aaf58f1dc6a6ae9d37fa8194b94/src/server/scripts/Custom/Transmog/Transmogrification.cpp#L392-L393
They block one hand transmogrification with main and off hand weapons.

There has been so much requests about this that I might make a setting.
However you must understand that some items are like the warglaives of azzinoth. The item model is made so it only fits the main hand and will not properly fit the off hand.

**Comment by selenir** [comment]
Still trying! :D

Any idea, how to enable transmoging to items with for ex. Chance on hit? http://www.wowhead.com/item=7717/ravager

**Comment by Rochet2** [comment]
Set `Transmogrification.IgnoreReqStats = 1` in config

**Comment by selenir** [comment]
Edited much code, worked, thank you :)

**Comment by Keader** [comment]
@Rochet2 I did the following:

```diff

diff --git a/src/server/scripts/Custom/Transmog/Transmogrification.cpp b/src/server/scripts/Custom/Transmog/Transmogrification.cpp
index e166534..9cd4d3a 100644
--- a/src/server/scripts/Custom/Transmog/Transmogrification.cpp
+++ b/src/server/scripts/Custom/Transmog/Transmogrification.cpp
@@ -388,9 +388,7 @@ bool Transmogrification::CanTransmogrifyItemWithItem(Player* player, ItemTemplat
     if (source->InventoryType != target->InventoryType)
     {
         if (source->Class == ITEM_CLASS_WEAPON &&
-            (IsRangedWeapon(target->Class, target->SubClass) != IsRangedWeapon(source->Class, source->SubClass) ||
-            source->InventoryType == INVTYPE_WEAPONMAINHAND ||
-            source->InventoryType == INVTYPE_WEAPONOFFHAND))
+            (IsRangedWeapon(target->Class, target->SubClass) != IsRangedWeapon(source->Class, source->SubClass)))
             return false;
         if (source->Class == ITEM_CLASS_ARMOR &&
             !((source->InventoryType == INVTYPE_CHEST && target->InventoryType == INVTYPE_ROBE) ||

```

Solves the problem of daggers however items like Warglaive of Azzinoth (main hand) do not work with sword (one hand). Tested with a Rogue

Items IDs: item = 32837 [Warglaive of Azzinoth] and item 50412 = [Bloodvenom Blade]

Is there any way to Unblock it?

**Comment by Keader** [comment]
```diff

diff --git a/src/server/scripts/Custom/Transmog/Transmogrification.cpp b/src/server/scripts/Custom/Transmog/Transmogrification.cpp
index e166534..9cd4d3a 100644
--- a/src/server/scripts/Custom/Transmog/Transmogrification.cpp
+++ b/src/server/scripts/Custom/Transmog/Transmogrification.cpp
@@ -388,9 +388,7 @@ bool Transmogrification::CanTransmogrifyItemWithItem(Player* player, ItemTemplat
     if (source->InventoryType != target->InventoryType)
     {
         if (source->Class == ITEM_CLASS_WEAPON &&
-            (IsRangedWeapon(target->Class, target->SubClass) != IsRangedWeapon(source->Class, source->SubClass) ||
-            source->InventoryType == INVTYPE_WEAPONMAINHAND ||
-            source->InventoryType == INVTYPE_WEAPONOFFHAND))
+            (IsRangedWeapon(target->Class, target->SubClass) != IsRangedWeapon(source->Class, source->SubClass)))
             return false;
         if (source->Class == ITEM_CLASS_ARMOR &&
             !((source->InventoryType == INVTYPE_CHEST && target->InventoryType == INVTYPE_ROBE) ||

```

Works for me , ty :+1:

**Comment by Rochet2** [comment]
Well, its not a side effect really, but you can transmogrify for example warglaives to the wrong hands

**Comment by irgc** [comment]
confirm!

all cods changed to and icant use get cod patched
not found >  a/src/server/scripts/Custom/Transmog/Transmogrification.cpp
is it > --- a/src/server/scripts/Custom/Transmog/Transmogrifier.cpp

how to fixed main hand and off hand for transmog all weapons!

What should be changed

**Comment by Rochet2** [comment]
@irgc The file is now at `/src/server/game/Entities/Item/Transmogrification.cpp`

**Comment by irgc** [comment]
@Rochet 

not found lines on /src/server/game/Entities/Item/Transmogrification.cpp

-            source->InventoryType == INVTYPE_WEAPONMAINHAND ||
-            source->InventoryType == INVTYPE_WEAPONOFFHAND))

can u give me patch for edit fixed?

**Comment by Rochet2** [comment]
@irgc must change
`(source->InventoryType == INVTYPE_WEAPON || source->InventoryType == INVTYPE_2HWEAPON)))))`
to
`(source->InventoryType == INVTYPE_2HWEAPON)))))`

**Comment by irgc** [comment]
i changed
but not work for me

icant transmog main hand and off hands ! to onehands - daggers - tow hands!

:(

**Comment by Rochet2** [comment]
Config for it implemented:
https://github.com/Rochet2/TrinityCore/commit/da23246497bbab50f7caa39ca27b53c95e2c8aa6
Enables 2h to 1h and any mixing of 1h

**Comment by irgc** [comment]
did you know you're so good?:)

Thanks a lot .
