### ISSUE TITLE
[Transmog] Gossip stuck

### ISSUE THREAD

**Issue by Keader** [Rochet2/TrinityCore#3]
Hello Rochet. Today testing transmog, I noticed the gossip hangs when the item ends to be "transformed."
I made a video to show the problem: https://youtu.be/2gpjRLOMvXA

Token entry: 22484

**Comment by Rochet2** [comment]
Can you try with the script here on the main post?
https://github.com/TrinityCore/TrinityCore/issues/10053

This is possibly a TC issue or similar.
Also could you post the TC version you use or something?

**Comment by Keader** [comment]
Trinity Core rev. https://github.com/TrinityCore/TrinityCore/commit/accab5451d3e62739e4aa376d25bc6623f0d3c52

**Comment by Keader** [comment]
Test you asked for: https://youtu.be/5-FmpOvJmgQ

**Comment by Rochet2** [comment]
The stuff is printed to the console : /

**Comment by Keader** [comment]
Sorry my mistake
New video: https://youtu.be/zPoF88-wjw0

**Comment by Rochet2** [comment]
Thanks a lot.
Was that a clean TC without other modifications?

Guess I need to reopen the issue

**Comment by Keader** [comment]
Yes TC Clean. The only modification is the Transmog :)

**Comment by Rochet2** [comment]
I am unable to reproduce the problem on
https://github.com/TrinityCore/TrinityCore/commit/accab5451d3e62739e4aa376d25bc6623f0d3c52 -your version
or on https://github.com/TrinityCore/TrinityCore/commit/0b1355b2800f8000dbf245cb035ac2bc9ba4a06e -latest atm

By using the latest diff - updated today to latest TC rev
(between https://github.com/Rochet2/TrinityCore/commit/0b1355b2800f8000dbf245cb035ac2bc9ba4a06e and https://github.com/Rochet2/TrinityCore/commit/c6a047003e2783282f670d26c8483437f66fa4d8)

Retry by downloading the latest diff and clean before building.

**Comment by Keader** [comment]
Sorry for the delay. With TC rev https://github.com/TrinityCore/TrinityCore/commit/e142c3b87397a84a9169c25bc211c80ce917d508 also not caught here, it worked perfectly
