### ISSUE TITLE
No show item to transmog

### ISSUE THREAD

**Issue by javmen50** [Rochet2/TrinityCore#5]
Hi, I donwload, compile and configure the transmog patch, but not work, the npc not show the items to transmogrification, press the update menu, and nothing, not work, any idea. Thank you
![wowscrnshot_072515_013331](https://cloud.githubusercontent.com/assets/13493455/8888191/9907e2e6-326d-11e5-8b7e-42f02bf0008e.jpg)
![procesos](https://cloud.githubusercontent.com/assets/13493455/8888197/b33939b2-326d-11e5-8ab1-be5c964ce5ed.jpg)

**Comment by Rochet2** [comment]
How did you install?
What items do you have in bags? Can you give me exact item entries?

Try with priest item sets 666 and 664

**Comment by javmen50** [comment]
Thank you for your answer, I understand, will hace both piece in bag, sorry
for my error. I'll delete the issue

2015-07-25 3:35 GMT-04:30 Rochet2 <notifications@github.com>:

> How did you install?
> What items do you have in bags? Can you give me exact item entries?
>
> Try with priest item sets 666 and 664
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rochet2/TrinityCore/issues/5#issuecomment-124819326>.
>



-- 
Javier I. Mendoza R.
