### ISSUE TITLE
Source item dose not exist

### ISSUE THREAD

**Issue by Regrad** [Rochet2/TrinityCore#53]
When you enter the npc menu, an inscription appears "Source item dose not exist"

Transmog items do not appear in the menu.

Branch 335  
last version of base and core.
Windows 10

**Comment by Regrad** [comment]
![wowscrnshot_050317_022755](https://cloud.githubusercontent.com/assets/790695/25643398/40be9cf8-2fa8-11e7-9e4a-780b7821d9b0.jpg)

**Comment by Rochet2** [comment]
Fixed in https://github.com/Rochet2/TrinityCore/commit/38265d514b98674ba92c108edd9d75ecd7f574d5
