### ISSUE TITLE
Transmog

### ISSUE THREAD

**Issue by DJBoxer** [Rochet2/TrinityCore#56]
**Description**:  Transmog needs updating for lastest commits

**Current behaviour**: Tell us what happens  fails to patch

**Expected behaviour**: Tell us what should happen instead   patches changeds where needed

**Steps to reproduce the problem**:

1.   update TC to this [commit
](https://github.com/TrinityCore/TrinityCore/commit/85a7d5ce9ac68b30da2277cc91d4b70358f1880d)

2.  then use git apply transmog.diff

3.  all patches say failed.

error: patch failed: src/server/game/DataStores/DBCStores.cpp:377
error: src/server/game/DataStores/DBCStores.cpp: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.h:29
error: src/server/game/Entities/Player/Player.h: patch does not apply
error: patch failed: src/server/game/Handlers/SpellHandler.cpp:26
error: src/server/game/Handlers/SpellHandler.cpp: patch does not apply
error: patch failed: src/server/scripts/Spells/spell_generic.cpp:39
error: src/server/scripts/Spells/spell_generic.cpp: patch does not apply

I`ve always used this transmog script before without any issue guessing it where headers and such has been changed

**Branch(es)**: 335/6x  335

**TC hash/commit**:  85a7d5ce9ac68b30da2277cc91d4b70358f1880d

**TDB version**:  TDB 335.63 

**Operating system**:  win10

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by gragonvlad** [comment]
Workeds !!!!

**Comment by gragonvlad** [comment]
Commit https://github.com/TrinityCore/TrinityCore/commit/2d2c71cc754f9f76111a150f0159e4b042feb145  
https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmogvendor.diff 
 TDB 335.63
Ubuntu Server 16.04.2
base/world.sql + TDB 335.63

**Comment by Rochet2** [comment]
I will update on weekend as usual.

**Comment by DJBoxer** [comment]
@gragonvlad thanks for info but I'm not talking about transmog vendor just the 3.3.5 blizzlike transmog.

@Rochet2 thank you.
