### ISSUE TITLE
Error Transmogrification for last TC 3.3.5

### ISSUE THREAD

**Issue by irgc** [Rochet2/TrinityCore#57]
Hi, this patch has a problem

i use   trinitycore 3.3.5 last cloner download 

Diff: https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmog.diff

use git apply for Transmogrification  but error lines..
fatal: corrupt patch at line 2396

src: trinitycore 3.3.5a last version download of cloner .

need to Transmogrification use just item on bag for hard server blizzlike..

Thanks if you could fix the patch

**Comment by Rochet2** [comment]
The patch should be fine.
Did you download it as instructed?
You should not copy paste the code to a file.

**Comment by irgc** [comment]
i know

and again test = error

Administrator@PARSVDS-NETWORK /c/TrinityCore
$ git pull rochet2 transmog
fatal: Not a git repository (or any of the parent directories): .git
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `__git_ps1)'

You can fix in the full patch format for the latest version. I miss everything

and 

place the downloaded transmog.diff to the source root folder
open git bash to source location
do git apply transmog.diff
use cmake and compile

fatal: corrupt patch at line 2396
bash: command substitution: line 1: syntax error near unexpected token `)'
bash: command substitution: line 1: `__git_ps1)'

Administrator@/c/TrinityCore


my src:

src: trinitycore 3.3.5a last version download of cloner .

I need this patch, what to do

:disappointed:

**Comment by Rochet2** [comment]
> fatal: Not a git repository (or any of the parent directories): .git

You should have cloned your repository through git.
If you did clone the source with git then you are using the git commands from the wrong folder.



> fatal: corrupt patch at line 2396

You are likely doing something to the patch that makes it fail.
How exactly are you downloading the patch?

**Comment by irgc** [comment]
hi 
open page
https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmog.diff
and copy cod + creat new file transmog.patch.patch and paste cods .

transmog.patch

git apply --reject transmog.patch

**Comment by Rochet2** [comment]
> and *copy cod* + creat new file transmog.patch and paste cods

This is exactly what you should NOT do.
The installation instructions tell you to right click the link instead and select "save as".

**Comment by irgc** [comment]
yes - sry - and ty

**Comment by Rochet2** [comment]
probably not atm.
