### ISSUE TITLE
[gomove] Problem with addon communication

### ISSUE THREAD

**Issue by Magnifikator** [Rochet2/TrinityCore#59]
I think because of this commit the gomove addon is not working anymore:
https://github.com/TrinityCore/TrinityCore/commit/508c9d2fc1b20dc2cb40df533e823e1dfe2becc3

Don't know what they have done there. 

However as long as the gomove addon is sending only custom GM commands .gomove (starting with a dot) may there is no need to send it with SendAddonMessage(). Instead try SendChatMessage(). It will not visible too.

If I write by hand a .gomove command for testing purpose into the chat console the addon is working.

Edit:
Just tested: With SendChatMessage() instead of SendAddonMessage() it works as before.

**Comment by Rochet2** [comment]
https://github.com/Rochet2/TrinityCore/commit/431fdefab6e4ac60e93b1fe2ef3f7f8c66f683ac
