### ISSUE TITLE
Transmogs disappearing on relog

### ISSUE THREAD

**Issue by Rochet2** [Rochet2/TrinityCore#60]
Someone at some point mentioned that transmogs would sometimes disappear on relog.
I have been unable to reproduce this problem, but this may fix it hopefully:
https://github.com/TrinityCore/TrinityCore/pull/20187

Maybe it was @demonid ?

**Comment by Demonid** [comment]
I did report this 2 years ago, since then i tested again on a newer version and didn't happen, so maybe this was a local issue or you fixed it years ago while doing improvements to your script.

**Comment by StygianTheBest** [comment]
I tested this module on AzerothCore and had no issues.

**Comment by Rochet2** [comment]
Report if this occurs again.
