### ISSUE TITLE
Transmog for 3.3.5

### ISSUE THREAD

**Issue by flaggi** [Rochet2/TrinityCore#64]
**Description**:
Transmog breaks set bonuses

**Current behaviour**: Tell us what happens
If I transmog a setpiece the setbonus is lost because the server nolonger recognizes the mogged piece as part of the set.

**Expected behaviour**: Tell us what should happen instead
2 and 4 piece setbonus should remain after mogging.

**Steps to reproduce the problem**:
1. equip atleast 2 pieces of a set
2. transmog one piece
3. setbonus is lost

**Branch(es)**: 335/6x  
3.3.5a.12340

**Operating system**:  
Debian 9

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rochet2** [comment]
From https://github.com/azerothcore/mod-transmog/issues/3#issuecomment-323596306
> Never confirmed to be true.
> What actually happens is that tooltips dont show the set bonuses properly since we fake that we have another item equipped. People do not actually test if the bonus itself is applied, they just see in the tooltip the visual bug of set bonus not applying.
> Even though the client says the set bonus is not active, the core still should properly handle applying the set bonus. This means that spells will proc and stats are there.
> 
> Please actually confirm with the stats and procs instead of relying on the tooltips.
> If the stats are missing then it is an issue somewhere. Otherwise its just a visual bug in the tooltip system we cannot properly avoid without client side edits (like patches or addons)

If you can show that it is indeed affecting stats and or procs then will investigate more.

**Comment by flaggi** [comment]
Thank you for the quick answer.
I Will do some immerse testing, the visual was the only proof i have of the
problem but the reason for finding it was actially that my character felt
more squishy after the transmog and when i started looking i noticed the
visual saying that the set wasn't active.


While i have your attention i'd like to ask for an idea about another issue
regarding reforging.
I tried building it last night but it only returns with error: No matching
function to call.
Attaching a screenshot.

Thank you in advance.
/Flaggi


Den 16 jan. 2018 12:40 skrev "Rochet2" <notifications@github.com>:

Closed #64 <https://github.com/Rochet2/TrinityCore/issues/64>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Rochet2/TrinityCore/issues/64#event-1425963151>, or mute
the thread
