### ISSUE TITLE
Reforge diff errors

### ISSUE THREAD

**Issue by GnaXi** [Rochet2/TrinityCore#66]
**Description**:
When I try to apply the diff for Reforging, I'm met with an error.

**Current behaviour**:
I get the following errors, when I try to apply the diff:
error: patch failed: .travis.yml:6
error: .travis.yml: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.cpp:12296
error: src/server/game/Entities/Player/Player.cpp: patch does not apply
error: patch failed: src/server/game/Entities/Player/Player.h:2139
error: src/server/game/Entities/Player/Player.h: patch does not apply
error: patch failed: src/server/scripts/Custom/custom_script_loader.cpp:16
error: src/server/scripts/Custom/custom_script_loader.cpp: patch does not apply

**Steps to reproduce the problem**:
Follow the instructions here:
https://github.com/Rochet2/TrinityCore/tree/reforging/src/server/scripts/Custom/Reforging

**Branch(es)**: 335/6x  
335

**Operating system**:  
Debian 9

**Comment by Rochet2** [comment]
You are not applying to a clean source.
Additionally your source can be too old or new compared to the version of reforging that you downloaded.

You should apply with `git apply --reject reforging.diff`
and apply the failed parts from generated `.rej` files manually.

There is little I can do to avoid issues with other patches or modifications you do to the source.
Scripts edit the same locations which means once you have one script others will fail and you must manually fix the code.
