### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by mirrox1337** [Rochet2/TrinityCore#68]
I got this error when compiling, Any clue?

../scripts/libscripts.a(custom_script_loader.cpp.o): In function `AddCustomScripts()':
/home/trinity/TrinityCore/src/server/scripts/Custom/custom_script_loader.cpp:33: undefined reference to `AddSC_Transmogrification()'
collect2: error: ld returned 1 exit status
src/server/worldserver/CMakeFiles/worldserver.dir/build.make:211: recipe for target 'src/server/worldserver/worldserver' failed
make[2]: *** [src/server/worldserver/worldserver] Error 1
CMakeFiles/Makefile2:1596: recipe for target 'src/server/worldserver/CMakeFiles/worldserver.dir/all' failed
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Rochet2** [comment]
did you run cmake?
