### ISSUE TITLE
Dress npc doesn't allow morph of the npc

### ISSUE THREAD

**Issue by razielvonchronos** [Rochet2/TrinityCore#69]
**Greeting Rochet,first of all I wanna tell you THANKS FOR ALL YOUR WORK,I CURRENTLY USE YOUR STUFF SINCE EVER AND LUV IT!**
So my problem is:
Tried to make a c++ script for a npc which on gossip case changes his display race
// Draenei
creature->SetDisplayId(20323);

**Current behaviour**: creature disapears,worldserver doesn't slow error 

**Expected behaviour**:  morph the creature to its new displayid?

**Steps to reproduce the problem**:

1.  Go to a creature that uses for example -61022 displayID
2.  Write .morph 20323 to morph it to Draenei
3.  Creature disapears and becomes untargetable.

**Branch(es)**: 335

**TC hash/commit**:  Commit hash:	c099174ff777d1bf5061f5cdc197ff17bd83fbb7

**TDB version**:  3.3.5

**Operating system**:  Windows 7 x64 Ultimate

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

**Comment by Rochet2** [comment]
https://github.com/Rochet2/TrinityCore/commit/1337fffa3c6a0b3e9ff1caf255b6f11b3e73483b

**Comment by razielvonchronos** [comment]
Thank you,you are the best ^,.,^ BTW if you have time,please check the support section on ac-web to help me out with your Item Gossip script :3 :)
