### ISSUE TITLE
NPC does not function as expected

### ISSUE THREAD

**Issue by Animalthug** [Rochet2/TrinityCore#74]
**Description:**

Can not get the NPC to display anything other then the "Greetings, (Player)"

**Current behaviour:**

Cloned, cmake, compiled
Checked settings in worldserver
Created the NPC with creature_transmogrify ScriptName. (due to the one provided in the instructions has an input error for column "InhabitType")

In-game
.add npc 190010
Talking to the NPC only displays "Greetings, (Player)"

**Expected behaviour:**

Clone, cmake, compile, 
load NPC sql file

In-game
.add NPC # 
Transmog equipment

**Steps to reproduce the problem:**

Follow these instructions
https://github.com/Rochet2/TrinityCore/tree/transmog/src/server/scripts/Custom/Transmog

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore rev. 2aa088bc78ff 2018-03-12 05:39:49 -0400 (3.3.5 branch) (Win64, Release, Static)

**TDB version:**  335.64

**Operating system:** Win10 64

**Comment by Rochet2** [comment]
Try this:
```sql
SET
@Entry = 190010,
@Name = "Warpweaver";

REPLACE INTO `creature_template` (`entry`, `modelid1`, `modelid2`, `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`, `scale`, `rank`, `dmgschool`, `baseattacktime`, `rangeattacktime`, `unit_class`, `unit_flags`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `AIName`, `MovementType`, `HoverHeight`, `RacialLeader`, `movementId`, `RegenHealth`, `mechanic_immune_mask`, `flags_extra`, `ScriptName`) VALUES
(@Entry, 19646, 0, @Name, "Transmogrifier", NULL, 0, 80, 80, 2, 35, 1, 1, 0, 0, 2000, 0, 1, 0, 7, 138936390, 0, 0, 0, '', 0, 1, 0, 0, 1, 0, 0, 'Creature_Transmogrify');
```

If that does not work..
Which method of installing transmogrification did you use? Did you use the diff, merging or cloning the whole repository?
Check Server.log and DBErrors.log for anything to do with 190010 or Creature_Transmogrify.

**Comment by Animalthug** [comment]
Thank you so much!
