### ISSUE TITLE
Recovering lost item via the mail remove the transmog

### ISSUE THREAD

**Issue by Killyana** [Rochet2/TrinityCore#77]
**Description:** If you get back lost items via the mail, transmogrification will be removed.

**Steps to reproduce the problem:**

1. Get you bags full
2. Use the equipment manager to change items until a transmog item disappear from the bag
3. Get the item back from the mail and notice the transmog is gone

**Comment by Rochet2** [comment]
should be fixed in https://github.com/Rochet2/TrinityCore/commit/4014c50e877fff7109d5252d2e55482aa6b82558
