### ISSUE TITLE
Transmog compile error

### ISSUE THREAD

**Issue by nyhmii** [Rochet2/TrinityCore#79]
**Description:**
Keep getting these errors when compiling after cmake

bool GossipHello(Player* player) override
bool GossipSelect(Player* player, uint32 /*menu_id*/, uint32 gossipListId) override
bool GossipSelectCode(Player* player, uint32 /*menu_id*/, uint32 gossipListId, const char* code) override

**Current behaviour:**

override error. method function declared with override does not override a base class?

**Expected behaviour:**

to compile.

**Steps to reproduce the problem:**

**Branch(es):**
3.3.5

**TC rev. hash/commit:** 
latest trinity rev.
fresh compile

Win64, RelWithDebInfo

**Operating system:**

**Comment by Rochet2** [comment]
Show the whole code that errors and give an actual TC commit you are on.
Your script is wrong or you are not on latest TC or you have otherwise messed up core/failed installation.

**Comment by nyhmii** [comment]
@Rochet2 the same code or 2 functions was for last years .63 rev as well. 
I'll take some screenshots. I've compile a fresh core, and the core works perfectly after compile. Get these errors when git bash, then cmake then compile.

They don't override the methods, though they are virtual declared

**Comment by Rochet2** [comment]
> the same code or 2 functions was for last years .63 rev as well

So you are using old scripts? TC changed their C++ gossip API so any gossip script from over .. 6 months ago or something like that is invalid / too old on newest TC. You would need to update your script,

> I'll take some screenshots

Will you also share them?

**Comment by Rochet2** [comment]
no replies, closing

**Comment by nyhmii** [comment]
Sorry! 
I've downloaded the .63 version of the core. had it last year and worked perfectly.

Now they've changed how gossips work with the merge on CreatureAI.... 

no I got that override error... I want to custom the script back to the .63 version ... can't find the updated .63 world_database structures ; /

**Comment by nyhmii** [comment]
This part 
bool GossipHello(Player* player) override
        {
            return OnGossipHello(player, me);
        }

ect.. x3 errors.. sincethey changed how it works. not on .63 it doesn't work anymore :(

**Comment by Rochet2** [comment]
I used this method to convert my scripts from old way to new way:
https://community.trinitycore.org/topic/13478-the-problem-with-the-custom-npc-script/?tab=comments#comment-82191

Try doing the opposite.
