### ISSUE TITLE
GOMove Doesn't Work

### ISSUE THREAD

**Issue by Runico** [Rochet2/TrinityCore#8]
GOMove Addons doesn't work on latest TC

**Comment by Rochet2** [comment]
Can you be more specific about what doesnt work for example?

**Comment by Runico** [comment]
@Rochet2, None of features works, but command ( .gomove 1 ) will add target object in selection list

**Comment by Rochet2** [comment]
Then the addon most likely works fine and the problem is in the core script or changes.

Did you edit Object.h or cpp files? How did you install the script?

**Comment by Runico** [comment]
Yes i did, normally what the readme was told

**Comment by Rochet2** [comment]
Most likely related to new guid changes in https://github.com/TrinityCore/TrinityCore/commit/dcb7082277447c21b11c4a1d59f105fa342c172e
GOMove is not yet updated past that.

**Comment by Rochet2** [comment]
Fixed.

**Comment by Runico** [comment]
Thank You
