### ISSUE TITLE
Cannot merge/apply diff for Multivendor 3.3.5a

### ISSUE THREAD

**Issue by iamreyne** [Rochet2/TrinityCore#85]
**Description:**

I receive error: patch failed: .travis.yml:2

Regarless of using the .diff or using auto merge.

**Expected behaviour:**

The file should merge successfully.

**Steps to reproduce the problem:**

1. Follow steps to add multivendor as listed on the multivendor README
2. Run git apply multivendor.diff OR git pull rochet2 multivendor
3. Receive error

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 

TrinityCore 9d066bb81b4c

**Operating system:** Debian 9

**Comment by Rochet2** [comment]
You have likely applied some other custom code already which is conflicting.
You can ignore the changes to travis.yml.
You can do this by using git apply --reject (do read online what this does).
or if you use git pull then you can resolve the merge conflicts by editing travis.yml.
