### ISSUE TITLE
dressnpcs can not merge with latest tc

### ISSUE THREAD

**Issue by qyh214** [Rochet2/TrinityCore#91]
**Description:** 

dressnpcs can not merge with latest tc(TrinityCore/TrinityCore@8f91a85aaa789276e0b9a6486ae96b978ec281d9),please update

**Current behaviour:**

can not merge

**Expected behaviour:**

can merge

**Steps to reproduce the problem:**

N/A

**Branch(es):**

3.3.5

**TC rev. hash/commit:** 
8f91a85aaa789276e0b9a6486ae96b978ec281d9

**Operating system:** win10 x64

**Comment by Rochet2** [comment]
fixed https://travis-ci.org/Rochet2/TrinityCore/builds/429131495
