### ISSUE TITLE
Transmog For Last Tc Not Work

### ISSUE THREAD

**Issue by Hir0shi** [Rochet2/TrinityCore#93]
Hi 

@Rochet2 

dont work transmog for last tc 3.3.5

<Details>
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_guild.cpp.o
/home/TrinityCore/src/server/game/DataStores/DBCStores.cpp:115:57: error: use of undeclared identifier
'ItemDisplayTemplateEntryfmt'; did you mean 'MailTemplateEntryfmt'?
DBCStorage sItemDisplayInfoStore(ItemDisplayTemplateEntryfmt);
^~~~~~~~~~~~~~~~~~~~~~~~~~~
MailTemplateEntryfmt
/home/TrinityCore/src/server/shared/DataStores/DBCfmt.h:90:16: note: 'MailTemplateEntryfmt' declared here
char constexpr MailTemplateEntryfmt[] = "nxxxxxxxxxxxxxxxxxssssssssssssssssx";
^
[ 26%] Building CXX object src/server/game/CMakeFiles/game.dir/DataStores/M2Stores.cpp.o
1 error generated.
src/server/game/CMakeFiles/game.dir/build.make:1577: recipe for target 'src/server/game/CMakeFiles/game.dir /DataStores/DBCStores.cpp.o' failed
make[2]: *** [src/server/game/CMakeFiles/game.dir/DataStores/DBCStores.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_honor.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_instance.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_learn.cpp.o
[ 26%] Building CXX object src/server/scripts/CMakeFiles/scripts.dir/Commands/cs_lfg.cpp.o
CMakeFiles/Makefile2:1197: recipe for target 'src/server/game/CMakeFiles/game.dir/all' failed
make[1]: *** [src/server/game/CMakeFiles/game.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
</Details>

**Comment by Hir0shi** [comment]
@Rochet2  !?!

**Comment by Rochet2** [comment]
Manually check that everything from the patch is applied exactly as is in the patch.
The error suggests that you are missing ItemDisplayTemplateEntryfmt.

**Comment by Hir0shi** [comment]
the last trinitycore

downloaded https://github.com/Rochet2/TrinityCore/compare/TrinityCore:3.3.5...transmog.diff

dont work, cant full builded.
error

Error 2 make[1]: *** Waiting for unfinished jobs....

**Comment by Hir0shi** [comment]
this error is for last tc !
and transmog patch need to updated!

can u tested on last?!

**Comment by Rochet2** [comment]
Tested compiling on https://github.com/TrinityCore/TrinityCore/commit/0a0312b705ecb1a318fd3abe545b571a3a349a9c
here is the result: https://travis-ci.com/Rochet2/TrinityCore3.3.5/builds/89235033
Looks good to me.
