### ISSUE TITLE
bug 255

### ISSUE THREAD

**Issue by Hir0shi** [Rochet2/TrinityCore#95]
hi
rochet

trasnmog not work for 255 level?

**Comment by Rochet2** [comment]
Yes it does.
If you have some issue I need a lot of information about the item you try to transmogrify and the item you try to use as source of transmogrification, your settings for transmogrification system and the character you try to transmog the item with.

**Comment by Hir0shi** [comment]
hi dear

yes i want use on fun server 255 , can u give me patch fix?

**Comment by Hir0shi** [comment]
Rochet
can give discord me?

i need to u please

**Comment by Hir0shi** [comment]
Rochet

example:
item custom 255

`
INSERT INTO `item_template` VALUES (270000, 2, 15, -1, 'Dagger', 6555, 0, 0, 0, 1, 0, 0, 13, -1, -1, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 10, 3, 25000, 4, 410000, 7, 410000, 1, 25000000, 36, 1200, 44, 16000, 3, 25000, 32, 6000, 38, 3000000, 45, 3000000, 0, 0, 2850000, 3550000, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 1800, 0, 0, 20262, 1, 0, 0, 0, 0, 0, 19255, 1, 0, 0, 0, 0, 0, 71188, 1, 0, 0, 0, 0, 0, 26615, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, '|cffbbbbbbMade test', 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 'internalitemhanler', 0, 0, 0, 0, 0, 0);
`

can't transmog
