### ISSUE TITLE
Multitrainer can not work!

### ISSUE THREAD

**Issue by qxpf666** [Rochet2/TrinityCore#98]
the last version erro:
GOSSIP_OPTION_TRAINER:: Player Suijio (GUID: 2) requested wrong gossip menu: 60001 at Creature: jane (Entry: 190030)

**Comment by qxpf666** [comment]
Multitrainer3.3.5

**Comment by Rochet2** [comment]
Does it work now?
https://github.com/Rochet2/TrinityCore/commit/ce7dc182594b49857a5300e2527bfc34f2f0f9ae

**Comment by qxpf666** [comment]
still not work,maybe MultitrainerExample.sql need update?

**Comment by Rochet2** [comment]
Should work now. comment if you have issues.

**Comment by qxpf666** [comment]
yes，it is ok，but still show that err

**Comment by Rochet2** [comment]
The way TC fixes that error is to use conditions to make the gossip options to only show to the players that can really access those options.
The error only shows when for example a non shaman tries to view a shaman only trainer option.
